name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Login to container registry (replace with your registry details)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push your Node.js application image
    - name: Build and Push Node.js Image
      run: |
        cd charts
        docker build -t ${{ secrets.DOCKER_USERNAME }}/your-nodejs-app:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/your-nodejs-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # Path to your GCP service account key
      CLUSTER_NAME: ${{ secrets.DEV_CLUSTER_NAME }}  # Replace with cluster names (dev, test, prod)
      HELM_CHART_RELEASE: your-nodejs-app  # Replace with your Helm chart release name
    defaults:
      run: |
        cd terraform/clusters/${{ env.CLUSTER_NAME }}
        # ... (other Terraform and ArgoCD commands)

    strategies:
      matrix:
        cluster: [ dev, test, prod ]  # Define your environments here
    steps:
    - uses: actions/checkout@v3

    # Apply Terraform configurations (replace with actual commands)
    - name: Apply Terraform for ${{ env.CLUSTER_NAME }} cluster
      run: |
        terraform init
        terraform apply -auto-approve

    # Deploy application using ArgoCD (replace with actual commands)
    - name: Deploy application to ${{ env.CLUSTER_NAME }} with ArgoCD
      run: |
        argocd app set your-nodejs-app \
          --helm \
          --file charts/your-nodejs-app/values.yaml \
          --revision ${{ github.sha }} \
          -p ${CLUSTER_NAME}
        argocd app approve your-nodejs-app -p ${CLUSTER_NAME}

  # Additional steps (optional)
  # - Run tests for your Node.js application
  # - Update Grafana dashboards

