apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.3.1
        ports:
        - containerPort: 9100
        volumeMounts:
        - name: host-root-path
          mountPath: /
      volumes:
      - name: host-root-path
        hostPath:
          path: /
---
apiVersion: v1
kind: ServiceAccount
name: node-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-exporter-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: node-exporter
  namespace: monitoring
roles:
- apiGroup: ""
  resources:
  - nodes
  - nodes/proxy
  verbs: ["get", "scrape"]
