apiVersion: appsv1
kind: Deployment
metadata:
  name: argocd
  labels:
    app: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd:v2.9.0
        ports:
        - containerPort: 8080
        volumeMounts:
